nome = input('Digite seu nome completo: ')
print(nome.upper())
print(nome.lower())
print(len(nome.replace(' ','')))
print(len(nome))
print(nome.split())
dividido = nome.split()
print(len(dividido[0]))
